version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DEPENDABOT_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-github
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    assignees:
      - dependabot[bot]
    reviewers:
      - Sergey-Xursevich
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    versioning-strategy: "auto"
